@extends('guides')
@section('title_guide')<title>Pyke</title>@endsection
@section('main_guide')   
                <h class="title_landing"><center>Pyke - carry(supp)</center></h>
                <div><img src="./images/pyke1.png" alt="Landing" class="guide-pic1"></div>
                <p class="guide_text1">Once a notorious harpooner, Pyke was always willing to hunt. His dream was to catch the dreaded jaull-fish - a monster who was rarely seen and only mentioned in legends. One day, his dream almost came true, but he lost the fight and go devoured.</p>
                <p class="guide_text2">  The crew presumed Pyke dead, but he really wasn't. He continued to hunt, but now interested in some bigger fish. The lying merchants, reckless bounty hunters and unworthy captains were the targets that could be found "on the list". Stalking through alleyways, lurking in the  shadows and swiftly bringing an end to those who wronged him - Pyke will stop at nothing to get his revenge on the living.<br>  Pyke is an assassin, who is most often played in the support position. His skill-set is very useful for protecting the AD carry and can function well even on low economy.<br>  Pyke's passive "Gift of the Drowned One's" lets you regenerate some of the health you lost when fighting enemy champions if you stay out of sight.<br>  Pyke's Q "Bone Skewer" is his bread-and-butter spell. You can tap it to quickly stab enemies in front of Pyke to deal massive damage and slow the target or hold it to start charging up.<br>  Pyke's W "Ghostwater Dive" makes him gain camouflage and bonus movement speed for 5 seconds. While using that ability, nearby enemies will get a notification that Pyke is close, and reveal him if they come in certain range.<br>  Pyke's E "Phantom Undertow" is a utility spell that grants both mobility and cc. Upon cast, Pyke dashes forward, leaving a phantom behind. After a brief delay, it returns to Pyke, dealing damage and stunning all targets hit by the<br>phantom for 1.5 seconds.</p>
                <p class="guide_text3">  Pyke's Ultimate "Death from Below" is a spell that makes this champion truly unique. After casting, Pyke blinks and damages all enemies hit in an X-shaped area, executing all targets that have less than a certain amount of health.</p>
                <div><img src="./images/pyke2.png" alt="Landing" class="guide-pic2"></div>
@endsection